# Generated by Django 4.2.10 on 2024-07-07 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('gender', models.CharField(blank=True, default=None, max_length=1)),
                ('street', models.CharField(default='', max_length=80)),
                ('postcode', models.CharField(default='', max_length=5)),
                ('city', models.CharField(default='', max_length=80)),
                ('country', models.CharField(default='', max_length=25)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('unokod', models.CharField(max_length=10)),
                ('day_of_birth', models.DateField(default=None, null=True)),
                ('personnr_lastnr', models.CharField(default='', max_length=4)),
                ('last_edit', models.DateField(verbose_name='Senaste Aktivitet')),
            ],
            options={
                'verbose_name_plural': 'client',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=80)),
                ('postcode', models.CharField(default='', max_length=5)),
                ('city', models.CharField(default='', max_length=80)),
                ('blocked_clients', models.ManyToManyField(to='backend.client')),
            ],
            options={
                'db_table': 'hosts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.ManyToManyField(to='backend.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('total_places', models.IntegerField()),
                ('type', models.CharField(choices=[('room', 'Room'), ('woman-only', 'Woman Only')], max_length=12)),
                ('host', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='backend.host')),
                ('requirements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.productrequirement')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.AddField(
            model_name='host',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region'),
        ),
        migrations.AddField(
            model_name='host',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.ManyToManyField(to='backend.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.region'),
        ),
        migrations.AddField(
            model_name='client',
            name='requirements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.clientrequirement'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Datum')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Plats')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.bookingstatus', verbose_name='Beskrivning')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.client', verbose_name='Namn')),
            ],
            options={
                'db_table': 'product_booking',
            },
        ),
        migrations.CreateModel(
            name='Available',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField(verbose_name='Datum')),
                ('places_left', models.IntegerField(default=0, verbose_name='Platser kvar')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='Bokning')),
            ],
            options={
                'db_table': 'product_available',
            },
        ),
    ]
