# Generated by Django 4.2.10 on 2024-06-17 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'room_types',
            },
        ),
        migrations.AlterModelTable(
            name='available',
            table='available_rooms',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_spots', models.IntegerField()),
                ('available_spots', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='backend.product')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.roomtype')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.room', verbose_name='Rum'),
            preserve_default=False,
        ),
    ]
