# Generated by Django 4.2.10 on 2024-06-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_roomtype_alter_available_table_alter_booking_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AlterModelTable(
            name='available',
            table='product_available',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='product_booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
