# Generated by Django 4.2.10 on 2024-06-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_booking_room_alter_available_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('woman-only', 'Woman Only')], max_length=12),
        ),
    ]
