# Generated by Django 4.2.10 on 2024-07-17 07:01

from django.db import migrations

def populate_invoice_statuses(apps, schema_editor):
    InvoiceStatus = apps.get_model('backend', 'InvoiceStatus')
    statuses = [
        ('open', 'Open'),
        ('paid', 'Paid'),
        ('void', 'Void'),
        ('uncollectible', 'Uncollectible'),
    ]
    for code, name in statuses:
        InvoiceStatus.objects.create(name=code)

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_invoicestatus_remove_invoice_paid_invoice_vat_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_invoice_statuses),
    ]
