# Generated by Django 4.2.10 on 2024-07-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_booking_booking_time_booking_end_date_and_more'),
        ('backend', '0004_alter_product_type'),
    ]

    operations = [
    ]
