# Generated by Django 4.2.10 on 2024-08-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_invoice_buyer_address_invoice_buyer_name_and_more'),
    ]

    operations = [
    ]
