# Generated by Django 5.0.6 on 2024-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_invoice_buyer_address_invoice_buyer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='blocked_clients',
            field=models.ManyToManyField(blank=True, to='backend.client'),
        ),
    ]
