# Generated by Django 4.2.10 on 2024-09-11 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_alter_host_blocked_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='caseworkers',
            field=models.ManyToManyField(related_name='caseworkers', to=settings.AUTH_USER_MODEL),
        ),
    ]
