# Generated by Django 4.2.10 on 2024-09-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_host_blocked_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_type', models.CharField(choices=[('Dubbelsäng över/under', 'Dubbelsäng över/under'), ('Singelsäng', 'Singelsäng'), ('Madrass', 'Madrass')], max_length=25)),
                ('room_location', models.CharField(choices=[('Sovsal', 'Sovsal'), ('Dubbelrum', 'Dubbelrum'), ('Eget rum', 'Eget rum')], max_length=20)),
                ('status', models.CharField(choices=[('Ledig', 'Ledig'), ('Upptagen', 'Upptagen'), ('Avstängd', 'Avstängd')], default='Ledig', max_length=10)),
            ],
            options={
                'db_table': 'sleeping_spaces',
            },
        ),
    ]
