# Generated by Django 4.2.10 on 2024-09-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_merge_20240830_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='blocked_clients',
            field=models.ManyToManyField(blank=True, to='backend.client'),
        ),
    ]
