# Generated by Django 4.2.10 on 2024-09-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_sleepingspace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepingspace',
            name='room_location',
        ),
        migrations.AddField(
            model_name='product',
            name='room_location',
            field=models.CharField(choices=[('Sovsal', 'Sovsal'), ('Dubbelrum', 'Dubbelrum'), ('Eget rum', 'Eget rum')], default='default_location', max_length=20),
            preserve_default=False,
        ),
    ]
