# Generated by Django 4.2.10 on 2024-09-13 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0008_host_caseworkers'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='host',
            name='caseworkers',
            field=models.ManyToManyField(related_name='caseworker_hosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
