# Generated by Django 4.2.10 on 2024-09-18 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0009_remove_sleepingspace_room_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='caseworkers',
            field=models.ManyToManyField(related_name='caseworker_hosts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sleepingspace',
            name='bed_type',
            field=models.CharField(choices=[('Dubbelsäng över', 'Dubbelsäng över'), ('Dubbelsäng under', 'Dubbelsäng under'), ('Singelsäng', 'Singelsäng'), ('Madrass', 'Madrass')], max_length=25),
        ),
    ]
