# Generated by Django 4.2.10 on 2024-09-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_host_caseworkers_alter_sleepingspace_bed_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('room', 'Room'), ('woman-only', 'Woman Only'), ('washingmachine', 'Washing Machine'), ('hygieneproducts', 'Hygiene Products'), ('breakfast', 'Breakfast'), ('dinner', 'Dinner'), ('storage', 'Storage')], max_length=16),
        ),
    ]
