# Generated by Django 5.0.6 on 2024-10-04 20:38

# Generated by Django 5.0.6 on 2024-10-04 20:16

from django.db import migrations


def update_booking_status_from_enum(apps, schema_editor):
    # Get the BookingStatus model
    BookingStatus = apps.get_model('backend', 'BookingStatus')

    # Create a list of descriptions based on the `State` enum values
    statuses = [
        "pending",
        "declined",
        "accepted",
        "checked_in",
        "in_queue",
        "reserved",
        "confirmed",
        "completed",
        "advised_against"]

    # Iterate through the statuses and add them to the BookingStatus table if they don't exist
    for description in statuses:
        BookingStatus.objects.get_or_create(description=description)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_bookable_alter_product_type'),
    ]

    operations = [
        # Placeholder operation
        migrations.RunPython(update_booking_status_from_enum),
    ]
