# Generated by Django 5.0.6 on 2024-10-04 20:38

# Generated by Django 5.0.6 on 2024-10-04 20:16

from django.db import migrations


def update_booking_status_from_enum(apps, schema_editor):
    # Get the BookingStatus model
    BookingStatus = apps.get_model('backend', 'BookingStatus')
    State = apps.get_model('backend', 'State')

    # Create a list of descriptions based on the `State` enum values
    status_objects = [
        BookingStatus(id=State.PENDING, description="pending"),
        BookingStatus(id=State.DECLINED, description="declined"),
        BookingStatus(id=State.ACCEPTED, description="accepted"),
        BookingStatus(id=State.CHECKED_IN, description="checked_in"),
        BookingStatus(id=State.IN_QUEUE, description="in_queue"),
        BookingStatus(id=State.RESERVED, description="reserved"),
        BookingStatus(id=State.CONFIRMED, description="confirmed"),
        BookingStatus(id=State.COMPLETED, description="completed"),
        BookingStatus(id=State.ADVISED_AGAINST, description="advised_against"),
    ]

    for status in status_objects:
        BookingStatus.objects.get_or_create(id=status.id, defaults={"description": status.description})


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_bookable_alter_product_type'),
    ]

    operations = [
        # Placeholder operation
        migrations.RunPython(update_booking_status_from_enum),
    ]
