# Generated by Django 5.0.6 on 2024-10-04 20:38

# Generated by Django 5.0.6 on 2024-10-04 20:16

from django.db import migrations


def update_booking_status_from_enum(apps, schema_editor):
    # Get the BookingStatus model
    BookingStatus = apps.get_model('backend', 'BookingStatus')

    # Create a list of descriptions based on the `State` enum values
    status_objects = [
        BookingStatus(id=1, description="pending"),
        BookingStatus(id=2, description="declined"),
        BookingStatus(id=3, description="accepted"),
        BookingStatus(id=4, description="checked_in"),
        BookingStatus(id=5, description="in_queue"),
        BookingStatus(id=6, description="reserved"),
        BookingStatus(id=7, description="confirmed"),
        BookingStatus(id=8, description="completed"),
        BookingStatus(id=9, description="advised_against"),
    ]

    for status in status_objects:
        BookingStatus.objects.get_or_create(id=status.id, defaults={"description": status.description})


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_product_bookable_alter_product_type'),
    ]

    operations = [
        # Placeholder operation
        migrations.RunPython(update_booking_status_from_enum),
    ]
