# Generated by Django 4.2.10 on 2024-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_update_booking_status_enum'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='flag',
            field=models.CharField(choices=[('OK', 'OK'), ('FLAG', 'Flag'), ('DANGER', 'Danger'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10),
        ),
    ]
