# Generated by Django 4.2.10 on 2024-10-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_client_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
