# Generated by Django 5.0.6 on 2024-10-21 21:57

from django.db import migrations

def set_default_flag_false(apps, schema_editor):
    Client = apps.get_model('backend', 'Client')
    clients = Client.objects.all()

    for client in clients:
        if client.flag != True:
            client.flag = False
            client.save()

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_client_flag'),
    ]

    operations = [
        migrations.RunPython(set_default_flag_false),
    ]
