# Generated by Django 4.2.10 on 2024-11-08 00:37

from django.db import migrations

def create_volunteer_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='volunteer')

class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_set_default_flag'),
    ]

    operations = [
        migrations.RunPython(create_volunteer_group),
    ]
