# Generated by Django 4.2.10 on 2024-11-08 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_volunteerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerHostAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(verbose_name='Startdatum')),
                ('end_date', models.DateField(null=True, verbose_name='Slutdatum')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.host')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_assignments', to='backend.volunteerprofile')),
            ],
        ),
    ]
