# Generated by Django 4.2.10 on 2024-12-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_volunteerhostassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
