# Generated by Django 5.1.8 on 2025-05-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resource',
            name='applies_to',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resource',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='resource',
            name='other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='target_group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
