# Generated by Django 5.1.8 on 2025-05-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('direktinsats', 'Direktinsats'), ('mottagning', 'Mottagning')], default='mottagning', max_length=30),
        ),
    ]
