# Generated by Django 5.1.8 on 2025-05-13 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_activity_volunteertask'),
        ('backend', '0020_resource_address_resource_applies_to_resource_email_and_more'),
    ]

    operations = [
    ]
