# Generated by Django 4.2.21 on 2025-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('target_group', models.CharField(blank=True, max_length=100)),
                ('other', models.TextField(blank=True)),
                ('applies_to', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
