# Generated by Django 5.1.8 on 2025-04-29 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_apikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIKey',
        ),
    ]
