# Generated by Django 4.2.10 on 2025-10-13 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='Test Activity', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='contact_person',
            field=models.CharField(default='Test Contact', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activity',
            name='optional_instructions',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='organization',
            field=models.CharField(default='Test Organization', max_length=255),
        ),
    ]
