

@startuml

title Deployment diagram for noQ application

' TODO

folder folder [
This is a <b>folder
----
You can use separator
====
of different kind
....
and style
]


database productionDB [
This is a <b>database
----
You can use separator
====
of different kind
....
and style
]

action action
actor actor
actor/ "actor/"
agent agent
artifact artifact
boundary boundary
card card
circle circle
cloud cloud
collections collections
component component
control control
database database
entity entity
file file
folder folder
frame frame
hexagon hexagon
interface interface
label label
node node
package package
person person
process process
queue queue
rectangle rectangle
stack stack
storage storage
usecase usecase
usecase/ "usecase/"

@enduml
