### Bearer token 
GET http://127.0.0.1:8000/api/bearer
Content-Type: application/application/json
Authorization: Bearer supersecret

### Users
GET http://127.0.0.1:8000/api/users
Content-Type: application/application/json
Cookie: sessionid=supersecret

### Hosts
GET http://127.0.0.1:8000/api/hosts
Content-Type: application/application/json

### Hosts
GET http://127.0.0.1:8000/api/hosts/78
Content-Type: application/application/json

### Products
GET http://127.0.0.1:8000/api/products/769
Content-Type: application/application/json

### Bookings
GET http://127.0.0.1:8000/api/bookings/8
Content-Type: application/application/json

### Available rooms
GET http://127.0.0.1:8000/api/available/2
Content-Type: application/application/json

### Book a room
POST http://127.0.0.1:8000/api/bookings
accept: application/json
content-type: application/json

{
    "start_date": "2024-02-02",
    "product_id": 769,
    "user_id": 111
}

### Available rooms
GET http://127.0.0.1:8000/api/hosts/ids
Content-Type: application/application/json
